version: 2
updates:
  # Root workspace
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "@maximedesogus"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      turbo:
        patterns:
          - "turbo"
          - "@turbo/*"
      dev-dependencies:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@types/*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  # Frontend Angular
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    reviewers:
      - "@maximedesogus"
    commit-message:
      prefix: "frontend"
      include: "scope"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
        update-types:
          - "minor"
          - "patch"
      material:
        patterns:
          - "@angular/material*"
          - "@angular/cdk"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "playwright*"
          - "@playwright/*"
          - "jsdom"

  # Backend NestJS
  - package-ecosystem: "npm"
    directory: "/backend-nest"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    reviewers:
      - "@maximedesogus"
    commit-message:
      prefix: "backend"
      include: "scope"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
          - "nestjs-*"
        update-types:
          - "minor"
          - "patch"
      supabase:
        patterns:
          - "@supabase/*"
          - "supabase"

  # Shared package
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    reviewers:
      - "@maximedesogus"
    commit-message:
      prefix: "shared"
      include: "scope"
    groups:
      validation:
        patterns:
          - "zod"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "@maximedesogus"
    commit-message:
      prefix: "ci"
