packages:
  - frontend
  - shared
  - backend-nest
  - landing
  - landing-next

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nestjs-pino
  - supabase
  - unrs-resolver
