name: Pulpe
options:
  bundleIdPrefix: app.pulpe
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  lottie-spm:
    url: https://github.com/airbnb/lottie-spm
    from: "4.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.5.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: Pulpe/Resources/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  Pulpe:
    type: application
    platform: iOS
    sources:
      - path: Pulpe
        excludes:
          - "**/.DS_Store"
      - path: PulpeWidget/Models
        excludes:
          - "**/.DS_Store"
      - path: PulpeWidget/Services
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: supabase-swift
        product: Supabase
      - package: lottie-spm
        product: Lottie
      - target: PulpeWidget
        embed: true
    entitlements:
      path: Pulpe/Pulpe.entitlements
      properties:
        com.apple.security.application-groups:
          - group.app.pulpe.ios
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.pulpe.ios
        INFOPLIST_FILE: Pulpe/Resources/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    info:
      path: Pulpe/Resources/Info.plist
      properties:
        CFBundleDisplayName: Pulpe
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - arm64
        ITSAppUsesNonExemptEncryption: false
        NSFaceIDUsageDescription: "Utilisez Face ID pour vous connecter rapidement et en toute sécurité."
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - pulpe
            CFBundleURLName: app.pulpe.ios
        UIBackgroundModes:
          - fetch
        BGTaskSchedulerPermittedIdentifiers:
          - app.pulpe.ios.widget-refresh

  PulpeWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: PulpeWidget
        excludes:
          - "**/.DS_Store"
      - path: Pulpe/Domain/Models
        excludes:
          - "**/.DS_Store"
      - path: Pulpe/Domain/Formulas
        excludes:
          - "**/.DS_Store"
      - path: Pulpe/Shared/Extensions
        excludes:
          - "**/.DS_Store"
          - "**/View+Extensions.swift"
      - path: Pulpe/Shared/Formatters
        excludes:
          - "**/.DS_Store"
      - path: Pulpe/Shared/Design
        excludes:
          - "**/.DS_Store"
    entitlements:
      path: PulpeWidget/PulpeWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.app.pulpe.ios
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.pulpe.ios.widget
        INFOPLIST_FILE: PulpeWidget/Info.plist
        SKIP_INSTALL: true
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ""
    info:
      path: PulpeWidget/Info.plist
      properties:
        CFBundleDisplayName: Pulpe Widget
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: XPC!
        CFBundleExecutable: $(EXECUTABLE_NAME)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  PulpeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PulpeTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Pulpe
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.pulpe.ios.tests
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        TARGETED_DEVICE_FAMILY: "1,2"

  PulpeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PulpeUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Pulpe
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.pulpe.ios.uitests
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        TARGETED_DEVICE_FAMILY: "1,2"

schemes:
  Pulpe:
    build:
      targets:
        Pulpe: all
        PulpeWidget: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  PulpeWidget:
    build:
      targets:
        PulpeWidget: all
    run:
      config: Debug
      askForAppToLaunch: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  PulpeTests:
    build:
      targets:
        PulpeTests: all
    test:
      config: Debug
      targets:
        - name: PulpeTests

  PulpeUITests:
    build:
      targets:
        PulpeUITests: all
    test:
      config: Debug
      targets:
        - name: PulpeUITests
