/**
 * Single source of truth for API error codes.
 * Used by both backend (error-definitions.ts) and frontend (api-error-localizer.ts).
 */
export const API_ERROR_CODES = {
  // Generic
  INTERNAL_SERVER: 'ERR_INTERNAL_SERVER',
  REQUIRED_DATA_MISSING: 'ERR_REQUIRED_DATA_MISSING',
  INVALID_ID_FORMAT: 'ERR_INVALID_ID_FORMAT',
  UNKNOWN: 'ERR_UNKNOWN',

  // Auth
  AUTH_TOKEN_MISSING: 'ERR_AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'ERR_AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'ERR_AUTH_UNAUTHORIZED',
  AUTH_SESSION_EXPIRED: 'ERR_AUTH_SESSION_EXPIRED',
  AUTH_USER_FETCH_FAILED: 'ERR_AUTH_USER_FETCH_FAILED',
  AUTH_CLIENT_KEY_MISSING: 'ERR_AUTH_CLIENT_KEY_MISSING',
  AUTH_CLIENT_KEY_INVALID: 'ERR_AUTH_CLIENT_KEY_INVALID',
  RECOVERY_KEY_NOT_CONFIGURED: 'ERR_RECOVERY_KEY_NOT_CONFIGURED',
  RECOVERY_KEY_INVALID: 'ERR_RECOVERY_KEY_INVALID',
  RECOVERY_KEY_ALREADY_EXISTS: 'ERR_RECOVERY_KEY_ALREADY_EXISTS',
  ENCRYPTION_KEY_CHECK_FAILED: 'ERR_ENCRYPTION_KEY_CHECK_FAILED',
  ENCRYPTION_REKEY_PARTIAL_FAILURE: 'ERR_ENCRYPTION_REKEY_PARTIAL_FAILURE',
  ENCRYPTION_REKEY_FAILED: 'ERR_ENCRYPTION_REKEY_FAILED',
  ENCRYPTION_SAME_KEY: 'ERR_ENCRYPTION_SAME_KEY',

  // Budget
  BUDGET_NOT_FOUND: 'ERR_BUDGET_NOT_FOUND',
  BUDGET_CREATE_FAILED: 'ERR_BUDGET_CREATE_FAILED',
  BUDGET_UPDATE_FAILED: 'ERR_BUDGET_UPDATE_FAILED',
  BUDGET_DELETE_FAILED: 'ERR_BUDGET_DELETE_FAILED',
  BUDGET_FETCH_FAILED: 'ERR_BUDGET_FETCH_FAILED',
  BUDGET_ALREADY_EXISTS: 'ERR_BUDGET_ALREADY_EXISTS',
  BUDGET_INVALID_MONTH: 'ERR_BUDGET_INVALID_MONTH',

  // Template
  TEMPLATE_NOT_FOUND: 'ERR_TEMPLATE_NOT_FOUND',
  TEMPLATE_CREATE_FAILED: 'ERR_TEMPLATE_CREATE_FAILED',
  TEMPLATE_UPDATE_FAILED: 'ERR_TEMPLATE_UPDATE_FAILED',
  TEMPLATE_DELETE_FAILED: 'ERR_TEMPLATE_DELETE_FAILED',
  TEMPLATE_FETCH_FAILED: 'ERR_TEMPLATE_FETCH_FAILED',
  TEMPLATE_LINES_CREATE_FAILED: 'ERR_TEMPLATE_LINES_CREATE_FAILED',
  TEMPLATE_LINES_FETCH_FAILED: 'ERR_TEMPLATE_LINES_FETCH_FAILED',
  TEMPLATE_LINE_NOT_FOUND: 'ERR_TEMPLATE_LINE_NOT_FOUND',
  TEMPLATE_LINE_UPDATE_FAILED: 'ERR_TEMPLATE_LINE_UPDATE_FAILED',
  TEMPLATE_LINE_DELETE_FAILED: 'ERR_TEMPLATE_LINE_DELETE_FAILED',
  TEMPLATE_ONBOARDING_RATE_LIMIT: 'ERR_TEMPLATE_ONBOARDING_RATE_LIMIT',
  TEMPLATE_ACCESS_FORBIDDEN: 'ERR_TEMPLATE_ACCESS_FORBIDDEN',
  TEMPLATE_LINE_ACCESS_FORBIDDEN: 'ERR_TEMPLATE_LINE_ACCESS_FORBIDDEN',
  TEMPLATE_LINE_CREATE_FAILED: 'ERR_TEMPLATE_LINE_CREATE_FAILED',
  TEMPLATE_LINE_FETCH_FAILED: 'ERR_TEMPLATE_LINE_FETCH_FAILED',
  TEMPLATE_LIMIT_EXCEEDED: 'ERR_TEMPLATE_LIMIT_EXCEEDED',
  TEMPLATE_IN_USE: 'ERR_TEMPLATE_IN_USE',
  TEMPLATE_LINES_BULK_UPDATE_FAILED: 'ERR_TEMPLATE_LINES_BULK_UPDATE_FAILED',
  TEMPLATE_LINES_BULK_OPERATIONS_FAILED:
    'ERR_TEMPLATE_LINES_BULK_OPERATIONS_FAILED',
  TEMPLATE_LINES_VALIDATION_FAILED: 'ERR_TEMPLATE_LINES_VALIDATION_FAILED',
  TEMPLATE_LINE_TEMPLATE_MISMATCH: 'ERR_TEMPLATE_LINE_TEMPLATE_MISMATCH',

  // Transaction
  TRANSACTION_NOT_FOUND: 'ERR_TRANSACTION_NOT_FOUND',
  TRANSACTION_CREATE_FAILED: 'ERR_TRANSACTION_CREATE_FAILED',
  TRANSACTION_UPDATE_FAILED: 'ERR_TRANSACTION_UPDATE_FAILED',
  TRANSACTION_DELETE_FAILED: 'ERR_TRANSACTION_DELETE_FAILED',
  TRANSACTION_FETCH_FAILED: 'ERR_TRANSACTION_FETCH_FAILED',
  TRANSACTION_BUDGET_MISMATCH: 'ERR_TRANSACTION_BUDGET_MISMATCH',
  TRANSACTION_BUDGET_LINE_MISMATCH: 'ERR_TRANSACTION_BUDGET_LINE_MISMATCH',
  TRANSACTION_VALIDATION_FAILED: 'ERR_TRANSACTION_VALIDATION_FAILED',

  // Budget Line
  BUDGET_LINE_NOT_FOUND: 'ERR_BUDGET_LINE_NOT_FOUND',
  BUDGET_LINE_CREATE_FAILED: 'ERR_BUDGET_LINE_CREATE_FAILED',
  BUDGET_LINE_UPDATE_FAILED: 'ERR_BUDGET_LINE_UPDATE_FAILED',
  BUDGET_LINE_DELETE_FAILED: 'ERR_BUDGET_LINE_DELETE_FAILED',
  BUDGET_LINE_FETCH_FAILED: 'ERR_BUDGET_LINE_FETCH_FAILED',
  BUDGET_LINE_BUDGET_MISMATCH: 'ERR_BUDGET_LINE_BUDGET_MISMATCH',
  BUDGET_LINE_WITH_TRANSACTIONS: 'ERR_BUDGET_LINE_WITH_TRANSACTIONS',
  BUDGET_LINE_VALIDATION_FAILED: 'ERR_BUDGET_LINE_VALIDATION_FAILED',

  // User
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  USER_UPDATE_FAILED: 'ERR_USER_UPDATE_FAILED',
  USER_FETCH_FAILED: 'ERR_USER_FETCH_FAILED',
  USER_PROFILE_UPDATE_FAILED: 'ERR_USER_PROFILE_UPDATE_FAILED',
  USER_ONBOARDING_UPDATE_FAILED: 'ERR_USER_ONBOARDING_UPDATE_FAILED',
  USER_ONBOARDING_FETCH_FAILED: 'ERR_USER_ONBOARDING_FETCH_FAILED',
  USER_SETTINGS_UPDATE_FAILED: 'ERR_USER_SETTINGS_UPDATE_FAILED',
  USER_SETTINGS_FETCH_FAILED: 'ERR_USER_SETTINGS_FETCH_FAILED',
  USER_ACCOUNT_DELETION_FAILED: 'ERR_USER_ACCOUNT_DELETION_FAILED',
  USER_ACCOUNT_BLOCKED: 'ERR_USER_ACCOUNT_BLOCKED',

  // Validation
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  ZOD_VALIDATION_FAILED: 'ERR_ZOD_VALIDATION_FAILED',

  // Database
  DATABASE_CONNECTION_FAILED: 'ERR_DATABASE_CONNECTION_FAILED',
  DATABASE_QUERY_FAILED: 'ERR_DATABASE_QUERY_FAILED',
  DATABASE_TRANSACTION_FAILED: 'ERR_DATABASE_TRANSACTION_FAILED',

  // Data Integrity
  DATA_INTEGRITY_VIOLATION: 'ERR_DATA_INTEGRITY_VIOLATION',

  // Resource State
  RESOURCE_STATE_INVALID: 'ERR_RESOURCE_STATE_INVALID',

  // Business Rule
  BUSINESS_RULE_VIOLATION: 'ERR_BUSINESS_RULE_VIOLATION',

  // Concurrent Access
  CONCURRENT_MODIFICATION: 'ERR_CONCURRENT_MODIFICATION',

  // Missing Dependency
  DEPENDENCY_NOT_FOUND: 'ERR_DEPENDENCY_NOT_FOUND',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'ERR_RATE_LIMIT_EXCEEDED',

  // Import/Export
  IMPORT_VALIDATION_FAILED: 'ERR_IMPORT_VALIDATION_FAILED',
  EXPORT_GENERATION_FAILED: 'ERR_EXPORT_GENERATION_FAILED',

  // Configuration
  CONFIGURATION_INVALID: 'ERR_CONFIGURATION_INVALID',

  // External Service
  EXTERNAL_SERVICE_UNAVAILABLE: 'ERR_EXTERNAL_SERVICE_UNAVAILABLE',

  // Currency
  CURRENCY_RATE_FETCH_FAILED: 'ERR_CURRENCY_RATE_FETCH_FAILED',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
