export { Header } from "./Header";
export { Hero } from "./Hero";
export { Solution } from "./Solution";
export { Features } from "./Features";
export { Platforms } from "./Platforms";
export { Roadmap } from "./Roadmap";
export { WhyFree } from "./WhyFree";
export { FinalCTA } from "./FinalCTA";
export { Footer } from "./Footer";
